stages:
  - security
  - quality
  - test
  - docs
  - publish

include:
- local: .gitlab-ci/.gitlab-shared.yml
- local: .gitlab-ci/.gitlab-security.yml
- local: .gitlab-ci/.gitlab-quality.yml
- local: .gitlab-ci/.gitlab-test.yml
- local: .gitlab-ci/.gitlab-docs.yml
- local: .gitlab-ci/.gitlab-publish.yml