services:
  base-api:
      build: .    # common Dockerfile
      image: nrtk-cdao
      ports:
          - "80:80"
      volumes:
        - ./tests/data/VisDrone2019-DET-test-dev-TINY:/root/data
        - ./output:/root/output
      command: ["poetry", "run", "uvicorn", "nrtk_cdao.api.app:app", "--host", "0.0.0.0", "--port", "80"]
  # AUKUS-api:
  #     build: .    # common Dockerfile
  #     image: nrtk-cdao
  #     ports:
  #         - "90:90"
  #     volumes:
  #       - ./tests/data/VisDrone2019-DET-test-dev-TINY:/root/data
  #       - ./output:/root/output
  #     command: ["poetry", "run", "uvicorn", "nrtk_cdao.api.aukus_app:app", "--host", "0.0.0.0", "--port", "90"]
