services:
  base-api:
      build: .    # common Dockerfile
      image: nrtk-cdao
      ports:
          - "8080:80"
      volumes:
        - ./output:/root/output
      command: ["poetry", "run", "uvicorn", "nrtk_cdao.api.app:app", "--host", "0.0.0.0", "--port", "80"]
  AUKUS-api:
      build: .    # common Dockerfile
      image: nrtk-cdao
      ports:
          - "8081:90"
      volumes:
        - ./output:/root/output
      environment:
        - NRTK_IP=http://base-api:80/
      command: ["poetry", "run", "uvicorn", "nrtk_cdao.api.aukus_app:AUKUS_app", "--host", "0.0.0.0", "--port", "90"]
