###############################################################################
# Stage -- Unit Testing
###############################################################################
# 
# Overrides:
# 
# 1) Installed "tools" extras
#    - Intentionally did not include maite-cpu as to not override torch gpu
# 2) nrtk-jatic specific notebooks.
#
###############################################################################

.test-setup:
  before_script:
    - !reference [.shared-setup, before_script]
    - poetry install --sync --only main,dev-testing --extras tools

notebooks:
  parallel:
    matrix:
      # Sequences combinatorically combine within a list entry
      - NOTEBOOK_DIR: "examples"
        NOTEBOOK_FILE: [
          "augmentations.ipynb",
          "daml/daml_example_notebook.ipynb",
        ]
      - NOTEBOOK_DIR: "examples/gradio"
        NOTEBOOK_FILE: [
          "nrtk-gradio.ipynb"
        ]