###############################################################################
# Stage -- Security Scanning
###############################################################################
# 
# Overrides:
# 
# 1) Installed "tools" extras
#    - Intentionally did not include maite-cpu as to not override torch gpu
#
###############################################################################

dependency_scanning:
  before_script:
    - !reference [.shared-setup, before_script]
    - poetry install --sync --only main,dev-linting,dev-testing,dev-docs --extras tools
