###############################################################################
# Stage -- Unit Testing
###############################################################################
# 
# Overrides:
# 
# 1) Installed "tools" extras
#    - Intentionally did not include maite-cpu as to not override torch gpu
# 2) nrtk-jatic specific notebooks.
#
###############################################################################

.test-setup:
  before_script:
    - !reference [.shared-setup, before_script]
    - poetry install --sync --only main,tests
    # This does not work with poetry install but does work with pip. Poetry
    # has a PR working on it and hopefully won't be too far into the future
    # https://github.com/python-poetry/poetry/pull/9553
    - poetry run pip install -e .[tools,headless,pybsm-headless]

notebooks:
  parallel:
    matrix:
      # Sequences combinatorically combine within a list entry
      - NOTEBOOK_DIR: "examples"
        NOTEBOOK_FILE: [
          "augmentations.ipynb",
          "jatic-perturbations-saliency.ipynb",
          "nrtk_brightness_perturber_demo.ipynb"
          # "daml/daml_example_notebook.ipynb", broken notebook
        ]
      - NOTEBOOK_DIR: "examples/gradio"
        NOTEBOOK_FILE: [
          "nrtk-gradio.ipynb"
        ]